Página História + ajuste footer
arthurfary/apa-website pull request #2
Opened 2023-11-25 15:46 UTC by MhPasini

-Criei a página da História conforme esta no design do Canva.

-Essa pagina tá 100% dinâmica p/ mobile

-Fiz um pequeno ajuste no footer para ele não aparecer em cima do bloco main.

2023-11-25 15:47 UTC, MhPasini commented
Página de História ✔

2023-11-25 21:34 UTC, arthurfary requested changes
Ficou tudo muito bom, vc fez igualzinho o do draft do design, mas acho que vamso ter que mudar um pouco pq ta tudo muito grande,a fonte e tal

Ex.:


![image](https://github.com/arthurfary/apa-website/assets/91761997/13d645b6-f584-420f-9daf-f2a07ad6d4d2)


Outra, ficou muito bom o negocio do mobile; responsivasso, veja só se no mibile vc consegue aumentar um pouco a fonte, por que vai ficar pequeno de mais no mobile

de resto, muito foda

resumo -> menor no desktop, maior no mobile


![image](https://github.com/arthurfary/apa-website/assets/91761997/7f9575d7-5c46-4476-8803-9cf1d0fc0e3a)

Dei um exemplo do mobile aqui, mas se n der pra fazer assim, nao faz mal, edixa um pouco menor no desktop e um pouco maior os texto no mobile deixando a responisvidade do jeit oque tá que ta massa

2023-11-26 18:22 UTC, MhPasini commented
Eu fiz as modificações, coloquei uma configuração para mobile(width < 720px) que reorganiza os elementos da tela.

Modifiquei o footer, coloquei um menu com links das páginas. (deixei comentado o código antigo do e-mail), depois decidimos qual será mantido.

2023-11-26 23:49 UTC, arthurfary requested changes
![image](https://github.com/arthurfary/apa-website/assets/91761997/eaf1102c-06b2-4685-9e37-b7a749908ee7)
ELE ESTA PERFEITO, menos quando pega a tela toda, por algum motivo

deve ser uma porcentagem zoada

outra

![image](https://github.com/arthurfary/apa-website/assets/91761997/83868c8e-9078-49a5-b2c3-dbe3af373a36)
acredito que é pra ficar um embaixo do outro assim, so puxa o verda tudo pra direita


ultiama cosia, no mobile
![image](https://github.com/arthurfary/apa-website/assets/91761997/e7aae303-3555-4f70-be55-366171e88e48)


o resto ta fantastico

2023-11-27 16:01 UTC, merged